### ISSUE TITLE
[Poetry] introduce `poetry-version` setting

### ISSUE THREAD

**Issue by Secrus** [Secrus/ossus#16]
Poetry should have a setting checking the version of itself against the project requirement of Poetry version. 

```toml
[tool.poetry]
...
poetry-version = ">=1.6"
```
